### ISSUE TITLE
Change required when upgrading to 2021.30000 series

### ISSUE THREAD

**Issue by mbechard** [satoruhiga/TouchDesigner-ShaderBuilder#4]
In the 2021.30000 of builds, the shCoeffs have been moved from the TDLight block into their own block since they are now backed by a storage buffer object that is directly filled by the GPU. So instead of `LightParams.shCoeffs` you will need to change your references to be `uTDEnvLightBuffers[index].shCoeffs`.

Thanks for making this amazing tool!

**Comment by satoruhiga** [comment]
Resolved shader compilation error issue with TouchDesigner 2022!
There are a few shading issues that are not right, so we will try to fix them on our end as well.
It seems to be working 80% of the time.

Thanks for all your absurdly hard work! Congratulations!!! 👏👏👏👏
